### ISSUE TITLE
Sorting on page views shows lowest first

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#276]
<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/78595058-a4242780-7849-11ea-915c-fcfec315a19a.jpg"></kbd>

@hellodeibu this is locally on my laptop.

**Comment by hellodeibu** [comment]
@adriaanvanrossum The two domains listed with `?` have no pageviews (locally) yet, right? Our DB engine defaults to showing `NULL` results before actual numbers, so when sorting by descending order these show up at the very top, as you can see here. This changes as soon as a site has at least one pageview, which should mean they'll have definitely been configured properly. Depending on what you like this can be kind of nice (highlighting sites that have not yet been configured/set up), but this might be less ideal for people that add multiple sites without fully setting them up yet though.

Would you like me to change this so that these sites with no pageviews are placed at the very end of the list?

**Comment by adriaanvanrossum** [comment]
If it’s an easy change I would do that. It makes more sense to have the NULL at the end I think.

**Comment by hellodeibu** [comment]
Alright, no problem!
