### ISSUE TITLE
Graph is not fully used on initial load

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#378]
<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/90877667-bf30a780-e3a4-11ea-8d94-dcbbe7ba127f.png"></kbd>

**Comment by hellodeibu** [comment]
The graph Y height is currently set based on both page views and visitors data, regardless of which one is shown, so that flicking/switching these data sets don't cause visual discrepancies. Do you think it's better if this behavior is changed so that the graph changes scales depending on which dataset you make visible?

**Comment by adriaanvanrossum** [comment]
Ah I see. I think it's okay if the scale changes when clicking on page views vs visitors. Then we can keep the current behavior when you click on the items below the graph.

**Comment by hellodeibu** [comment]
Related issue: #395

**Comment by hellodeibu** [comment]
Adjusted now so that the scale changes if only the visitors dataset is being shown, as it was before! 

![graph-scaling](https://user-images.githubusercontent.com/18850/92325768-106cb680-f088-11ea-9ae2-8f8f5a8df805.gif)

**Comment by adriaanvanrossum** [comment]
Perfect!
