### ISSUE TITLE
Pages is still missing when customer is logged in

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#392]
What is loading, WHEN CONNECTED.:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1079135/92017300-daf85e00-ed53-11ea-94b8-d7331cd13ab6.png">

And what is then displayed, WHEN CONNECTED.

The "Pages" is missing, which is expected ONLY when NOT connected.

![image](https://user-images.githubusercontent.com/1079135/92017273-d16ef600-ed53-11ea-908b-acff61f6f9e5.png)

via Khodl

**Comment by hellodeibu** [comment]
This is probably due to the particular site having the `hide top pages` option enabled. As what these settings are set to are sent back by the API, the dashboard doesn't know until it gets its first result back, hence the switch. 

For the first page load we can probably have it do a sort of double check where the frontend also checks for these settings, but for subsequent loads (if, for example, you switch from looking at stats of one site to another site without reloading the page) this behavior can't be changed, as the settings can vary per site. 

It might be better to have a different "initial load" state that doesn't show these separate areas with individual loading indicators and instead shows one loading indicator until the initial data is available, do you think that would be a good solution?

**Comment by Khodl** [comment]
The problem is not that the title is displayed and then hidden.  The `hide top pages` is indeed enabled and this behaviour is expected for the *public* pages. But I'm connected, I'm the owner of the page, and therefore I should still be able to see that, similar to the current version.

Basically:
_if **(user is connected AND user is admin of this website) OR** `hide top page` disabled: show
else: hide_

The bold part is missing in the new version.

**Comment by adriaanvanrossum** [comment]
Ah, perfectly explained. I get it now. Thanks!
