### ISSUE TITLE
Graphs with gaps at start or end need to have zero fills

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#410]
✅  Current dashboard:

https://simpleanalytics.com/simpleanalytics.com/referrers/marc.io?start=2020-08-20&end=2020-09-18

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/93589919-e4b5ce80-f9ad-11ea-8f6c-d89d21f58bf9.png"></kbd>

🔴 Beta:

http://localhost:3000/simpleanalytics.com?from=2020-08-18&to=2020-09-17&referrals=marc.io

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/93589955-f4351780-f9ad-11ea-9841-d3fe7373ffd6.png"></kbd>

In beta the graph should be more aligned to the right. It's missing data at the start so it starts at the start. That's wrong.

**Comment by hellodeibu** [comment]
The dashboard now pads the incomplete data out as you've suggested! 

As an aside, it might be good to have the API return data for the entire range specified instead of only what it has data for? At least now the dashboard should pad things out even if it doesn't get everything it expects. 

![image](https://user-images.githubusercontent.com/18850/94353586-b458e900-00ad-11eb-9914-41202b1909eb.png)

I've tested this in a few scenarios but more tests (especially with more timezone variations) will be good to ensure everything works as it should now.

**Comment by hellodeibu** [comment]
Turns out this is not fully implemented just yet; visitors data seems to not have its zero padding visible (only page views), and when looking at the daily view the right-side is not properly padded out yet. Fixes incoming!

**Comment by hellodeibu** [comment]
Only the day view's end-of-day padding was a slight issue. A fix has been made! 

As it turns out the visitors data works correctly, I was just looking at the year overview and there's no data visible from before the feature actually launched. This sounds decidedly obvious in hindsight, as it always does :joy:. Still, a useful reminder, as I've added add a nice annotation at that date for anyone else that might look at their data around that date range and ends up wondering about the same thing I did.

Both fix and minor improvement are done and pending deploy!
