### ISSUE TITLE
Something is still wrong with period in datepicker vs graph

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#412]
1. Gap in data
1. Time range in graph is different from datepicker

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/93607624-dd9cb980-f9c9-11ea-9e2c-6f38a367f33a.png"></kbd>

http://localhost:3000/simpleanalytics.com?from=2020-05-19&to=2020-06-18

**Comment by adriaanvanrossum** [comment]
Probably because there is no data from before:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/93607898-3b310600-f9ca-11ea-8dbc-a5e3bcd2bfd2.png"></kbd>

The chart should start later.

**Comment by hellodeibu** [comment]
@adriaanvanrossum could you give this another try with the recent-most version and let me know if it looks good now? Point 2 should be fixed now, but I can't be certain if point 1 was due to the same bug (timezone parsing, which resulted in incorrect graph labels and whatnot), or if this is something else.

> Probably because there is no data from before
> The chart should start later.

This due to older data not being imported yet, right? Or do you mean there should be a limit or block of some kind applied to the frontend?

**Comment by adriaanvanrossum** [comment]
It think this is all good now.
