### ISSUE TITLE
Filter by page broken (beta)

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#414]
Selecting a page only changes url and title, but doesn't filter data.

<img width="1152" alt="Screenshot 2020-09-24 at 20 43 22" src="https://user-images.githubusercontent.com/5655500/94187235-f7e20600-fea7-11ea-8fcb-8e71c656e7ee.png">

**Comment by adriaanvanrossum** [comment]
I think this has something to do with the pages being hidden for the public. Will look into this, thanks!

Because it works for https://beta.simpleanalytics.com/simpleanalytics.com/open

**Comment by adriaanvanrossum** [comment]
Hm, while testing our simpleanalytics.com website with pages hidden it does not show this bug:

![image](https://user-images.githubusercontent.com/1079135/94813962-fad57d00-03f8-11eb-9c12-f4cac620991b.png)

**Comment by hellodeibu** [comment]
As it turned out this was an issue with the filtering not happening on the normalized paths, but it indeed also exposed another issue where you could view stats of a specific path if you tried visiting the specific page while top pages were hidden, even if you were not the owner. Both these issues have fixes now and are pending deployment. Thanks so much for reporting this!
