### ISSUE TITLE
Can't delete referral traffic with plusses

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#418]
![image](https://user-images.githubusercontent.com/1079135/94457880-7a730a00-01b5-11eb-85c3-fcc48aea9481.png)

**Comment by alinacsava** [comment]
Same issue for params without plusses

**Comment by adriaanvanrossum** [comment]
Ah, it's probably the spaces as well. Which are encoded as `%20`.

**Comment by alinacsava** [comment]
Yeah, it seems so.

**Comment by adriaanvanrossum** [comment]
I updated this logic to decode any encode characters. Did the same for incoming data, so every utm code will be saved decoded. It might be that this would not work for "old" data (that is, before now). We should add a way to delete utm_source data as well, I think. Let me see if that's easy to do now.

**Comment by adriaanvanrossum** [comment]
I think this is fixed now for all future data. I also added a feature where you can search on all UTM codes as well:



<kbd><img width="698" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96451952-9f88f480-1218-11eb-947b-11166e2f4269.png"></kbd>

**Comment by alinacsava** [comment]
I tried to clean at https://simpleanalytics.com/select-website/clean, starting with a term that included plusses https://simpleanalytics.com/fontsarena.com?start=2019-10-20&end=2020-10-19&utmSources=Guf%2BYfbthf%2Bba%2BZbifbcyf%2BGlcf
But I get an error:

<img width="856" alt="Screenshot 2020-10-19 at 16 09 30" src="https://user-images.githubusercontent.com/5655500/96462537-f648fb00-1225-11eb-883f-822db09492a3.png">

Same happened when I tried to clean this https://simpleanalytics.com/fontsarena.com?start=2019-10-20&end=2020-10-19&utmSources=localhost%3A8080%2Ffltra%2Fwall%2F1

<img width="910" alt="Screenshot 2020-10-19 at 16 16 07" src="https://user-images.githubusercontent.com/5655500/96462931-72dbd980-1226-11eb-9926-3b2821d15037.png">

Could it be because they're UTM sources/terms/etc without referrer?

**Comment by adriaanvanrossum** [comment]
Thanks for testing, deployed a new version where plusses and spaces should be allowed.

**Comment by alinacsava** [comment]
Now adding plusses is ok and I get to next step, but I get another error

<img width="864" alt="Screenshot 2020-10-19 at 16 46 26" src="https://user-images.githubusercontent.com/5655500/96467776-96ede980-122b-11eb-9b62-1370576742dc.png">

Tbh I have no idea where that random string comes from (doesn't have a referrer), so I also tried deleting as UTM campaign and the other options not just UTM term, but same result.

**Comment by adriaanvanrossum** [comment]
I think you'll need UTM source for this. Could you check that?

**Comment by alinacsava** [comment]
Not sure I understand. That string is from UTM source list https://simpleanalytics.com/fontsarena.com?utmSources=Guf%2BYfbthf%2Bba%2BZbifbcyf%2BGlcf&period=year

**Comment by adriaanvanrossum** [comment]
Ah, I already know why. It's not working because it's old data. So in the database we have some UTM sources with the `Guf%2BYfbthf%2Bba%2BZbifbcyf%2BGlcf` but now we store and check for `Guf+Yfbthf+ba+Zbifbcyf+Glcf`. I can manually add this for you.

I tried to add it manually, but I does not seem to work. Let me keep this issue open and debug further.

**Comment by adriaanvanrossum** [comment]
I was able to hide them for you. I just added the UTM source `Guf+Yfbthf+ba+Zbifbcyf+Glcf` and it worked. So I think if you just search for it with UTM source, it should work as expected.

They are now gone from your dashboard: https://simpleanalytics.com/fontsarena.com?utmSources=Guf%2BYfbthf%2Bba%2BZbifbcyf%2BGlcf&period=year

Let me know if it doesn't work for others.

**Comment by alinacsava** [comment]
Thank you, Adriaan! Worked ok for all others I tried now, including the one with localhost I mentioned earlier. I don't have another one with plusses to test, but I don't see why it wouldn't work ok like the others. We can close this issue for good. :)

**Comment by adriaanvanrossum** [comment]
Perfect!
