### ISSUE TITLE
Cannot delete traffic from certain referrers

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#426]
The referrers are mentioned here: https://t.me/c/1188685865/2145

**Comment by adriaanvanrossum** [comment]
It's happening because of a query timeout from the old database. It's something that will be fixed in the new dashboard. I did increase the timeout time, but it's not always enough. I don't want to increase it more at the moment because other processes need that time as well.

In the new dashboard we can add exclude referrers by a simple string so you don't have to actually delete the data. Which is super nice because it's super fast. I will keep this issue open for now.

**Comment by alinacsava** [comment]
It wasn't enough, I tried deleting again without success. But it's ok, it can wait until beta is out, those referrers are an insignificant portion of the traffic.

I did delete something on beta, can confirm it's super fast :)

**Comment by alinacsava** [comment]
This issue is true also for when trying to delete traffic from an ip or multi level subdomains. (maybe because both have more than two dots?)

**Comment by alinacsava** [comment]
It's fixed in the latest version, so I'm closing this. Thanks!
