### ISSUE TITLE
Time on page does not show when referral is selected

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#553]
[With filtering on referrer](https://simpleanalytics.com/simpleanalytics.com?start=2021-03-22&end=2021-03-28&referral=docs.simpleanalytics.com) it doesn't show time on page:

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/1079135/112818396-0fe44d80-90b6-11eb-9be5-f01176eec8ec.png">

With [`utm-source`](https://simpleanalytics.com/simpleanalytics.com?start=2021-03-22&end=2021-03-28&utm-source=istheshipstillstuck.com) or other filters seem to work fine.

**Comment by jibsaramnim** [comment]
Could this be because the `referral` changes for a subsequent click from a remote referral to a self referral (`istheshipstillstuck.com` on first visit, `simpleanalytics.com` on every subsequent click), which means it can't calculate the time on page as no "end" hits are found matching the referral filter criteria? If so, I wonder how we can make the ES query work to only care for referrals on first-but-not-subsequent hits, do you have any ideas that might help steer me in the right direction?

**Comment by adriaanvanrossum** [comment]
Isn't the referral part using a different endpoint in ES? Maybe we forgot to add the `duration_seconds:median` to it? Let's not spent too much time on this for now. Roles are more important :)

**Comment by jibsaramnim** [comment]
@adriaanvanrossum I'm not sure if this has been fixed (somehow?) already, but could you try again on your end? It seems like ToP is showing up when filtering on referrals too, at least in my testing here locally and on live :thinking:

**Comment by adriaanvanrossum** [comment]
I think it's fixed!
